package com.orangehrm.tests;

import com.orangehrm.base.BaseTest;
import com.orangehrm.pages.DashboardPage;
import com.orangehrm.pages.LoginPage;
import com.orangehrm.pages.PimPage;
import com.orangehrm.utils.ConfigReader;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class AddEmployeeTest extends BaseTest {

    private PimPage pimPage;
    private static final String FIRST_NAME = "Rahul";
    private static final String LAST_NAME = "Deshmukh_AutoQA";

    @BeforeMethod(alwaysRun = true)
    public void navigateToPim() {
        LoginPage loginPage = new LoginPage(driver);
        DashboardPage dashboard = loginPage.loginAs(
                ConfigReader.get("validUsername"),
                ConfigReader.get("validPassword"));
        pimPage = dashboard.goToPim();
    }

    /** TC_PIM_01: Adding an employee with mandatory fields only should succeed and
     *  show an auto-generated Employee Id. */
    @Test(priority = 1)
    public void testAddEmployeeWithMandatoryFields() {
        pimPage.clickAddEmployee();
        pimPage.enterEmployeeName(FIRST_NAME, LAST_NAME);

        String generatedId = pimPage.getAutoGeneratedEmployeeId();
        Assert.assertFalse(generatedId.isEmpty(), "Employee Id was not auto-generated");

        pimPage.clickSave();
        Assert.assertTrue(pimPage.isSuccessToastDisplayed(), "Success toast not shown after adding employee");
    }

    /** TC_PIM_02: An employee added via TC_PIM_01 (or otherwise present) can be found
     *  through the Employee List search. */
    @Test(priority = 2)
    public void testSearchExistingEmployee() {
        pimPage.searchEmployeeByName(FIRST_NAME + " " + LAST_NAME);
        Assert.assertTrue(pimPage.getSearchResultCount() > 0,
                "Search returned no results for a name expected to exist: " + FIRST_NAME + " " + LAST_NAME);
    }

    /** TC_PIM_03: Searching for a name that does not exist returns zero rows
     *  (validates the "No Records Found" negative path). */
    @Test(priority = 3)
    public void testSearchNonExistentEmployee() {
        pimPage.searchEmployeeByName("Zzzznonexistentemployee123");
        Assert.assertEquals(pimPage.getSearchResultCount(), 0,
                "Expected zero results for a name that should not exist");
    }
}
