package com.orangehrm.pages;

import com.orangehrm.utils.ConfigReader;
import com.orangehrm.utils.WaitUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import java.util.List;

public class PimPage {

    private final WebDriver driver;
    private final int wait = ConfigReader.getInt("explicitWait");

    private final By addEmployeeButton = By.xpath("//button[text()=' Add ']");
    private final By firstNameField = By.name("firstName");
    private final By lastNameField = By.name("lastName");
    private final By employeeIdField = By.xpath("//label[text()='Employee Id']/../following-sibling::div//input");
    private final By saveButton = By.xpath("//button[@type='submit']");
    private final By successToast = By.cssSelector(".oxd-toast-content--success");
    private final By employeeListSearchName = By.xpath("//label[text()='Employee Name']/../following-sibling::div//input");
    private final By searchButton = By.xpath("//button[text()=' Search ']");
    private final By employeeListRows = By.cssSelector(".oxd-table-card");
    private final By deleteIconOnRow = By.xpath(".//button[@title='Delete']");
    private final By deleteConfirmButton = By.xpath("//button[text()=' Yes, Delete ']");
    private final By loadingSpinner = By.className("oxd-loading-spinner");

    public PimPage(WebDriver driver) {
        this.driver = driver;
    }

    public void clickAddEmployee() {
        WaitUtils.waitForClickable(driver, addEmployeeButton, wait).click();
    }

    public void enterEmployeeName(String firstName, String lastName) {
        WaitUtils.waitForVisibility(driver, firstNameField, wait).sendKeys(firstName);
        WaitUtils.waitForVisibility(driver, lastNameField, wait).sendKeys(lastName);
    }

    public String getAutoGeneratedEmployeeId() {
        return WaitUtils.waitForVisibility(driver, employeeIdField, wait).getAttribute("value");
    }

    public void clickSave() {
        WaitUtils.waitForClickable(driver, saveButton, wait).click();
        // AJAX save spinner appears then disappears - wait it out before asserting the toast.
        waitForSpinnerToDisappearIfPresent();
    }

    public boolean isSuccessToastDisplayed() {
        return WaitUtils.waitForVisibility(driver, successToast, wait).isDisplayed();
    }

    public void searchEmployeeByName(String fullName) {
        WaitUtils.waitForVisibility(driver, employeeListSearchName, wait).sendKeys(fullName);
        WaitUtils.waitForClickable(driver, searchButton, wait).click();
        waitForSpinnerToDisappearIfPresent();
    }

    public int getSearchResultCount() {
        List<WebElement> rows = driver.findElements(employeeListRows);
        return rows.size();
    }

    /** Deletes the first row in the current employee list and handles the
     *  "Are you sure you want to delete the selected record?" confirmation dialog
     *  (a modal, not a native JS alert, but demonstrates the wait-then-confirm pattern). */
    public void deleteFirstResult() {
        List<WebElement> rows = driver.findElements(employeeListRows);
        if (rows.isEmpty()) {
            throw new IllegalStateException("No employee rows found to delete.");
        }
        rows.get(0).findElement(deleteIconOnRow).click();
        WaitUtils.waitForClickable(driver, deleteConfirmButton, wait).click();
        waitForSpinnerToDisappearIfPresent();
    }

    private void waitForSpinnerToDisappearIfPresent() {
        try {
            WaitUtils.waitForInvisibility(driver, loadingSpinner, wait);
        } catch (Exception ignored) {
            // Spinner may already be gone before we check - that's fine.
        }
    }
}
